theme: jekyll-theme-slate
title: Magic Label Paint 
logo: /iconfinder_Synchronize_131872.png
description: <iframe width="560" height="315" src="https://www.youtube.com/embed/m0N1C22AFdc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
baseurl: /MLPaintWeb
