theme: jekyll-theme-slate
title: Magic Label Paint 
name: Transforming the hand labeling experience for deep learning
tagline: Image segment labeing with ML-assist
logo: /iconfinder_Synchronize_131872.png
description: <iframe width="644" height="362" src="https://www.youtube.com/embed/m0N1C22AFdc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
baseurl: /MLPaintWeb
